### ISSUE TITLE
THE UPDATED GVIEW DOES NOT DISPPLAY BLAST ATLAS RINGS 

### ISSUE THREAD

**Issue by gilmahu** [phac-nml/gview#1]
Dear All, 

I have been using Gview for a while now. Recently the site has been out of service but now that it is back, it is not functioning as usual. 
I run a Blast atlas analysis as I used to and there was no preview nor jnlp file to download. That is fine because the result files are now in a separate zip file. However, when I open the executable GVIW and uploads the task file (annotated reference) followed by the gss style file and the result gff files, nothing comes. 
Moreover, when I try to run the file called QuickLunch.sh it also did not work. 
NB: My java is working fine. 

Does anyone know what the issue is?

**Comment by apetkau** [comment]
Hello @gilmahu . If this is an issue about a specific job on GView Server (https://server.gview.ca/) then please send an email to BioInfo-Support@phac-aspc.gc.ca with the job id. Thank you.

**Comment by gilmahu** [comment]
Dear Aaron, 
I have sent emails about the same issue and I hope to hear from you soon
Best regards Gildas 

Yaovi Mahuton GildasHounmanou, PhD 

Post-doc

 

University of Copenhagen

Faculty of Health and MedicalSciences 

Section for Food Safety and Zoonoses

Department of Vetrinary and AnimalSciences

Stigbøjlen 4, 1870 Frederiksberg, DK

 

Work phone: +4535326882

Mobile Phone: +4552641293

Skype: hounmanou

Email:gil@sund.ku.dk ; gilmahu@yahoo.fr

 

    Le jeudi 12 novembre 2020 à 15:51:21 UTC+1, Aaron Petkau <notifications@github.com> a écrit :  
 
 


Hello @gilmahu . If this is an issue about a specific job on GView Server (https://server.gview.ca/) then please send an email to BioInfo-Support@phac-aspc.gc.ca with the job id. Thank you.

**Comment by gilmahu** [comment]
Hi @apetkau You have closed my issue here but nobody seems to be attending to the email I sent to the address provided for almost a week now.
