### ISSUE TITLE
NO EMAIL RESPONSES 

### ISSUE THREAD

**Issue by gilmahu** [phac-nml/gview#2]
Hi Developers,
Is there any possibility to get responses from this email: BioInfo-Support@phac-aspc.gc.ca ? 
There seems to be nobody answering but issues raised here are being closed.

**Comment by ericenns** [comment]
Hi @gilmahu, as stated previously this is not the place to ask for support. Our lab is currently focused on the Canadian COVID response, as such email requests will be delayed.
